name: Test-Code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  testing-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v2

      - name: Single Greet
        run: echo Iniciando P.U. con Jest :D!!!!
        
      - name: Install / Config Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas con Jest
        run: npm test
